# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 05:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 5, 19, 5, 10, 18, 375959, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
